# Numpy -  multidimensional data arrays

---

Prof. Dr.-Ing. Antje Muntzinger, Hochschule für Technik Stuttgart

antje.muntzinger@hft-stuttgart.de

---

This notebook is based on [http://github.com/jrjohansson/scientific-python-lectures](http://github.com/jrjohansson/scientific-python-lectures).


## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [1]:
import numpy as np

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuple
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `np.array` function.

In [2]:
# a vector: the argument to the np.array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [3]:
# a matrix: the argument to the np.array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides. `ndarray` stands for “n-dimensional array”, n=1 is a vector, n=2 a matrix etc.

In [4]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` np.arrays is only their shapes. We can get information about the shape of an np.array by using the `ndarray.shape` property.

In [5]:
v.shape

(4,)

In [6]:
M.shape

(2, 2)

The number of elements in the np.array is available through the `ndarray.size` property:

In [7]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [8]:
np.shape(M)

(2, 2)

In [9]:
np.size(M)

4

So far the `numpy.ndarray` looks awfully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [10]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [11]:
# M[0,0] = "hello" # will raise an error

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [12]:
# create a range

x = np.arange(0, 10, 1) # arguments: start, stop, step

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

#### random data

In [14]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[0.19622447, 0.75891048, 0.46432705, 0.53309022, 0.65842865],
       [0.77341133, 0.27588025, 0.99430037, 0.95154515, 0.41929501],
       [0.2154553 , 0.69749375, 0.88022243, 0.66945079, 0.73803787],
       [0.15751471, 0.21944168, 0.72962705, 0.68541681, 0.30359453],
       [0.89337386, 0.24224491, 0.98311466, 0.69142113, 0.16936977]])

In [15]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 0.04722924,  0.3887169 ,  0.48154869, -1.01886941,  0.11876888],
       [ 0.20895415,  0.22956559,  1.49472777, -0.02785173, -0.51107139],
       [-0.2698603 ,  0.24305196, -0.26523797,  0.22516643, -0.50991208],
       [-0.25698599,  0.2654979 , -0.22625413,  1.2213122 , -0.25390885],
       [ 2.79134691,  0.0675609 , -0.6412362 , -1.00762599,  1.63564515]])

#### diag

In [16]:
# a diagonal matrix
M = np.diag([1,2,3,4])
M

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### zeros and ones

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Manipulating arrays

### Indexing

We can index elements in an np.array using square brackets and indices:

In [19]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [20]:
# M is a matrix, or a 2 dimensional np.array, taking two indices 
M[1,1]

2

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [21]:
M

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
M[1]

array([0, 2, 0, 0])

The same thing can be achieved with using `:` instead of an index: 

In [23]:
M[1,:] # row 1

array([0, 2, 0, 0])

In [24]:
M[:,1] # column 1

array([0, 2, 0, 0])

We can assign new values to elements in an array using indexing:

In [25]:
M[0,0] = 7

In [26]:
M

array([[7, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [28]:
M

array([[ 7,  0, -1,  0],
       [ 0,  0, -1,  0],
       [ 0,  0, -1,  0],
       [ 0,  0, -1,  4]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [29]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [30]:
A[1:3]

array([2, 3])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [31]:
A[::] # lower, upper, step all take the default values

array([1, 2, 3, 4, 5])

In [32]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([1, 3, 5])

In [33]:
A[:3] # first three elements

array([1, 2, 3])

In [34]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the np.array (positive index from the beginning):

In [35]:
A = np.array([1,2,3,4,5])

In [36]:
A[-1] # the last element in the array

5

In [37]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [38]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [39]:
# a block from the original array
A[1:5, 2:4]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43]])

In [40]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

**TODO 1**: Create a 1D NumPy array with numbers 0 to 9. Then, extract the first three elements, the last two elements, and every second element of the array.

In [41]:
# YOUR CODE GOES HERE

a = np.arange(10)
print("Array:", a)
print("First 3 elements:", a[:3])
print("Last 2 elements:", a[-2:])
print("Every 2nd element:", a[::2])

Array: [0 1 2 3 4 5 6 7 8 9]
First 3 elements: [0 1 2]
Last 2 elements: [8 9]
Every 2nd element: [0 2 4 6 8]


**TODO 2**: 3d arrays work just like 3d arrays, but with an additional index. You can think of a 3D array as a batch of matrices, or a 3D cuboid. Slice the given 3D array, using the slicing techniques used above: Extract a 2x2x2 sub-array from the original array, and print the result.

In [43]:
# Given 3D numpy array
array_3d = np.array([[[ 0,  1,  2],
                      [ 3,  4,  5],
                      [ 6,  7,  8]],
                     
                     [[ 9, 10, 11],
                      [12, 13, 14],
                      [15, 16, 17]],
                     
                     [[18, 19, 20],
                      [21, 22, 23],
                      [24, 25, 26]]])

# YOUR CODE GOES HERE

array_3d[:2, :2, :2]


array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

In [20]:
# Playground to access individual sub-arrays of array_3d

array_3d[:, 0 , 1]
array_3d[0, :, :] # equal array_3d[0]
array_3d[:2, :, 2]

array([[ 2,  5,  8],
       [11, 14, 17]])

## Linear algebra

In [2]:
import numpy as np

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [3]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [4]:
v1 * 2

array([0, 2, 4, 6, 8])

In [5]:
v1 + 2

array([2, 3, 4, 5, 6])

In [6]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Element-wise array-array operations

When we add, subtract, multiply and divide np.arrays with each other, the default behaviour is **element-wise** operations:

In [7]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [8]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [9]:
v1

array([0, 1, 2, 3, 4])

In [10]:
v1 * v1

array([ 0,  1,  4,  9, 16])

**TODO 3**: Create two 1D NumPy arrays, each with 5 elements. Perform element-wise addition, subtraction, and multiplication of these arrays.

In [11]:
# YOUR CODE GOES HERE

import numpy as np

# Zwei Arrays mit je 5 Elementen
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Elementweise Operationen
addition = a + b
subtraction = a - b
multiplication = a * b

# Ausgabe
print("Addition:     ", addition)
print("Subtraktion:  ", subtraction)
print("Multiplikation:", multiplication)


Addition:      [11 22 33 44 55]
Subtraktion:   [ -9 -18 -27 -36 -45]
Multiplikation: [ 10  40  90 160 250]


### Matrix algebra

What about matrix multiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [12]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [13]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [14]:
np.dot(v1, v1)

30

Equivalently, we can use the `matmul` notation:

In [15]:
np.matmul(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

Here is a more compact notation of matrix multiplication using the `@` symbol:

In [16]:
A @ A

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [17]:
A @ v1

array([ 30, 130, 230, 330, 430])

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.

In [18]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [19]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [20]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [21]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [22]:
# inner product
v.T * v

matrix([[30]])

In [23]:
# with matrix objects, standard matrix algebra applies
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

If we try to add, subtract or multiply objects with incompatible shapes we get an error:

In [24]:
v = np.matrix([1,2,3,4,5,6]).T

In [25]:
np.shape(M), np.shape(v)

((5, 5), (6, 1))

In [67]:
# M * v # will raise an error

**TODO 4:** Apply matrix multiplication in 4 different ways to the matrices A and B given below.

In [26]:
# Given matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1], [1], [1]])

# YOUR CODE GOES HERE

# Methode 1: np.dot()
result1 = np.dot(A, B)

# Methode 2: @-Operator (Python 3.5+)
result2 = A @ B

# Methode 3: np.matmul()
result3 = np.matmul(A, B)

# Methode 4: A.dot(B)
result4 = A.dot(B)

# Ausgabe
print("np.dot(A, B):\n", result1)
print("A @ B:\n", result2)
print("np.matmul(A, B):\n", result3)
print("A.dot(B):\n", result4)


np.dot(A, B):
 [[ 6]
 [15]]
A @ B:
 [[ 6]
 [15]]
np.matmul(A, B):
 [[ 6]
 [15]]
A.dot(B):
 [[ 6]
 [15]]


### Calculations with higher-dimensional data

When functions such as `min`, `max`, etc. are applied to a multidimensional np.arrays, it is sometimes useful to apply the calculation to the entire np.array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [2]:
import numpy as np

In [3]:
m = np.random.rand(3,3)
print(m)

[[0.39107028 0.54047201 0.82805206]
 [0.92868539 0.3448264  0.06890757]
 [0.77606284 0.24353012 0.98734223]]


In [4]:
# global max
m.max()

0.9873422256911597

In [24]:
# max in each column
m.max(axis=0)

array([0.92868539, 0.54047201, 0.98734223])

In [25]:
# max in each row
m.max(axis=1)

array([0.82805206, 0.92868539, 0.98734223])

In [26]:
# mean value in each row
m.mean(axis=1)

array([0.58653145, 0.44747312, 0.6689784 ])

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.


**TODO 5**: Create a 1D NumPy array with 10 random integers between 1 and 100. Find and print the minimum, maximum, sum, and mean of the array.

In [56]:
# YOUR CODE GOES HERE
np.random.seed(42)
n = np.random.randint(1, 101, size=10)# 10 random integers between 1 and 100 
print("Array with 10 randoms between 1 and 100:", n)
print("Minimum:", n.min())
print("Maximum:", n.max())
print("Sum:", n.sum())
print("Mean:", n.mean())


Array with 10 randoms between 1 and 100: [52 93 15 72 61 21 83 87 75 75]
Minimum: 15
Maximum: 93
Sum: 634
Mean: 63.4


## Reshaping and resizing np.arrays

The shape of an Numpy np.array can be modified without copying the underlying data, which makes it a fast operation even for large np.arrays.

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
n, m = A.shape
print(n,m)

2 3


In [59]:
B = A.reshape((1,n*m))
B

array([[1, 2, 3, 4, 5, 6]])

In [60]:
B[0,0:5] = 5 # modify the np.array

B

array([[5, 5, 5, 5, 5, 6]])

In [61]:
A # and the original variable is also changed. B is only a different view of the same data

array([[5, 5, 5],
       [5, 5, 6]])

We can also use the function `flatten` to make a higher-dimensional np.array into a vector. But this function creates a copy of the data.

In [62]:
B = A.flatten()

B

array([5, 5, 5, 5, 5, 6])

In [63]:
B[0:5] = 10

B

array([10, 10, 10, 10, 10,  6])

In [64]:
A # now A has not changed, because B's data is a copy of A's, not referring to the same data

array([[5, 5, 5],
       [5, 5, 6]])

Numpy allows to give one of the new dimension parameters as -1, indicating that this dimension has to be adapted such that 'The new shape should be compatible with the original shape'. Here are some examples:

In [65]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [66]:
a.shape

(2, 2)

In [1]:
b = a.reshape(1, -1) # the reshaped np.array is 2-dimensional and has 1 row
b

array([[1, 2, 3, 4]])

In [2]:
b.shape

(1, 4)

In [3]:
c = a.reshape(-1) # the reshaped np.array is 1-dimensional (note the single square brackets in the output indicating a 1d np.array)
c

array([1, 2, 3, 4])

In [4]:
c.shape

(4,)

In [5]:
d = a.reshape(-1, 1) # the reshaped np.array is 2-dimensional and has 1 column
d

array([[1],
       [2],
       [3],
       [4]])

In [6]:
d.shape

(4, 1)

In [90]:
# e = a.reshape(-1, -1) # this does not work

**TODO 6:** Flatten the 3D array `array_3d` into a 1D array. Then, reshape the 1D array back to a 2D array with 3 rows and 4 columns. Print the 1D and 2D arrays.

In [ ]:
# Given 3D array
array_3d = np.array([[[ 0,  1],
                      [ 2,  3]],

                     [[ 4,  5],
                      [ 6,  7]],

                     [[ 8,  9],
                      [10, 11]]])

# YOUR CODE GOES HERE





## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [ ]:
A = np.array([[1, 2], [3, 4]])

A

In [93]:
# now B is referring to the same array data as A 
B = A 

In [ ]:
# changing B affects A
B[0,0] = 10

B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [96]:
B = np.copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

In [ ]:
A

## Iterating over np.array elements

Generally, we want to avoid iterating over the elements of np.arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an np.array:

In [ ]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = np.array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

When we need to iterate over each element of an np.array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

In [ ]:
# each element in M is now squared
M

## Further reading

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.